owner: AodhanLP
repo: upptime-status

sites:
  - name: Jenkins
    url: https://status.jenkins.io/
  - name: Circle CI
    url: https://status.circleci.com/
  - name: AWS
    url: https://health.aws.amazon.com/health/status
  - name: GitHub
    url: https://www.githubstatus.com/
  - name: Atlassian
    url: https://status.atlassian.com/
  - name: Slack
    url: https://status.slack.com/
  - name: Google Stuff
    url: https://www.google.com/appsstatus/dashboard/
  - name: Sage
    url: https://status.sage.com/

status-website:
  baseUrl: /upptime-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  faviconSVG: https://learningpool.com/favicon.svg
  theme: dark
  name: Upptime Status
  introTitle: "**Upptime Status** was set up to track the status on dependant services, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/AodhanLP/upptime-status).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
