owner: AodhanLP
repo: upptime-status

sites:
- name: Jenkins
  url: https://jenkins.learningpool.com/login
- name: dev
  url: https://qa.curatrdev.com/
- name: UAT
  url: https://aodhanwade-uat.headstreamlxp.info/
- name: prod
  url: https://hal9001.curatr3.com/
- name: Stream LXP
  url: https://learningpool.streamlxp.com/
- name: Stream LXP US
  url: https://learningpool-us.streamlxp.com/
- name: Learning Locker
  url: https://saas.learninglocker.net/
- name: Learning Locker US
  url: https://saas-us.learninglocker.net/
- name: Waves
  url: https://waves.learningpool.com/
assignees:
  - AodhanLP

status-website:
  baseUrl: /upptime-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  faviconSVG: https://learningpool.com/favicon.svg
  theme: dark
  name: Upptime Status
  introTitle: "**Upptime Status**"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/AodhanLP/upptime-status) to track Learning Pool sites including our Jenkins server, Stream, Learning Locker, and Waves sites.
  navbar:
    - title: Status
      href: /upptime-status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
